In [18]:
#للتحديث المستمر عند اي تعديل 
%load_ext autoreload
%autoreload 2

#لاضافة مسار مجلد المشروع 
import sys
import os

sys.path.append(os.path.abspath("G:\Programming\Computer Vision\Smart-humanitarian-aid-distribution-system-project"))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [19]:
from src.preprocessing.load_data import load_data

df = load_data(r"G:\\Programming\\Computer Vision\\Smart-humanitarian-aid-distribution-system-project\\data\\raw\\families_200.xlsx")

df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   FamilyID       200 non-null    int64
 1   SpecialCase    200 non-null    int64
 2   Income         200 non-null    int64
 3   FamilyMembers  200 non-null    int64
 4   Housing        200 non-null    object
 5   Region         200 non-null    object
dtypes: int64(4), object(2)
memory usage: 9.5+ KB

In [ ]:

df.head()

   FamilyID  SpecialCase  Income  FamilyMembers  Housing Region
0         1            0     827              5      جيد  South
1         2            1     786              5  جيد جدا  North
2         3            1    1848              4      سيئ   West
3         4            0    1643              8      جيد   East
4         5            0    1645              8      سيئ  South

In [21]:

# for watching a missing value in a columns

from src.preprocessing.clean_data import clean_data


df = clean_data(df)
df.isnull().sum()

FamilyID         0
SpecialCase      0
Income           0
FamilyMembers    0
Housing          0
Region           0
dtype: int64

In [23]:
from src.features.feature_engineering import feature_engineering

df = feature_engineering(df)

df.head()
df.columns

Index(['FamilyID', 'SpecialCase', 'Income', 'FamilyMembers', 'Housing',
       'Region_East', 'Region_North', 'Region_South', 'Region_West'],
      dtype='object')

In [24]:
df[['SpecialCase','Income','FamilyMembers','Housing']].isnull().sum()

SpecialCase      0
Income           0
FamilyMembers    0
Housing          0
dtype: int64

In [25]:
from src.scoring.priority_score import calculate_priority_score

df = calculate_priority_score(df)

df[['PriorityScore', 'PriorityLevel']]

     PriorityScore PriorityLevel
0             0.47           Low
1             0.82          High
2             0.75        Medium
3             0.36           Low
4             0.39           Low
..             ...           ...
195           0.17           Low
196           0.67        Medium
197           0.57        Medium
198           0.75        Medium
199           0.72        Medium

[200 rows x 2 columns]

In [26]:
# الجدول الناتج 
df.head()

,FamilyID,SpecialCase,Income,FamilyMembers,Housing,Region_East,Region_North,Region_South,Region_West,PriorityScore,PriorityLevel
0,1,0,1.0,0.5,0.7,False,False,True,False,0.47,Low
1,2,1,1.0,0.5,0.2,False,True,False,False,0.82,High
2,3,1,0.5,0.5,1.0,False,False,False,True,0.75,Medium
3,4,0,0.5,0.7,0.7,True,False,False,False,0.36,Low
4,5,0,0.5,0.7,1.0,False,False,True,False,0.39,Low

In [27]:
# الجدول الناتج بعد ترتيبهم حسب الاولوية
df = df.sort_values(by='PriorityScore', ascending=False)
df.head()

,FamilyID,SpecialCase,Income,FamilyMembers,Housing,Region_East,Region_North,Region_South,Region_West,PriorityScore,PriorityLevel
137,138,1,1.0,0.7,1.0,False,False,True,False,0.94,High
74,75,1,1.0,0.7,0.7,False,False,False,False,0.91,High
104,105,1,1.0,0.5,1.0,False,False,True,False,0.90,High
140,141,1,1.0,0.5,1.0,False,False,False,True,0.90,High
165,166,1,1.0,0.5,1.0,False,False,True,False,0.90,High

In [28]:
#اذا بدي اعلى 50 بالاولوية   
df = df.sort_values(by='PriorityScore', ascending=False)
top_50 = df.head(50)

top_50

,FamilyID,SpecialCase,Income,FamilyMembers,Housing,Region_East,Region_North,Region_South,Region_West,PriorityScore,PriorityLevel
137,138,1,1.0,0.7,1.0,False,False,True,False,0.94,High
74,75,1,1.0,0.7,0.7,False,False,False,False,0.91,High
104,105,1,1.0,0.5,1.0,False,False,True,False,0.90,High
140,141,1,1.0,0.5,1.0,False,False,False,True,0.90,High
165,166,1,1.0,0.5,1.0,False,False,True,False,0.90,High
134,135,1,1.0,0.5,1.0,False,False,True,False,0.90,High
192,193,1,1.0,0.5,1.0,False,True,False,False,0.90,High
43,44,1,1.0,0.5,0.7,False,False,False,True,0.87,High
92,93,1,1.0,0.5,0.7,True,False,False,False,0.87,High
69,70,1,1.0,0.5,0.7,False,True,False,False,0.87,High
9,10,1,1.0,0.5,0.7,False,False,True,False,0.87,High
139,140,1,1.0,0.5,0.7,False,False,False,False,0.87,High
182,183,1,1.0,0.2,1.0,False,True,False,False,0.84,High
88,89,1,1.0,0.5,0.2,True,False,False,False,0.82,High
116,117,1,1.0,0.5,0.2,True,False,False,False,0.82,High
1,2,1,1.0,0.5,0.2,False,True,False,False,0.82,High
52,53,1,1.0,0.2,0.7,False,False,False,True,0.81,High
50,51,1,1.0,0.2,0.7,False,False,False,False,0.81,High
73,74,1,0.5,0.7,0.7,False,True,False,False,0.76,Medium
198,199,1,0.5,0.5,1.0,False,True,False,False,0.75,Medium
53,54,1,0.5,0.5,1.0,False,False,False,False,0.75,Medium
67,68,1,0.5,0.5,1.0,False,False,False,False,0.75,Medium
35,36,1,0.5,0.5,1.0,False,False,True,False,0.75,Medium
2,3,1,0.5,0.5,1.0,False,False,False,True,0.75,Medium
91,92,1,0.5,0.5,0.7,False,False,False,True,0.72,Medium
118,119,1,0.5,0.5,0.7,False,False,True,False,0.72,Medium
25,26,1,0.5,0.5,0.7,False,False,True,False,0.72,Medium
199,200,1,0.5,0.5,0.7,False,False,True,False,0.72,Medium
191,192,1,0.5,0.5,0.7,False,False,False,True,0.72,Medium
183,184,1,0.5,0.5,0.7,True,False,False,False,0.72,Medium
126,127,1,0.5,0.5,0.7,False,True,False,False,0.72,Medium
178,179,1,0.5,0.5,0.7,False,False,True,False,0.72,Medium
33,34,1,0.5,0.5,0.2,False,False,True,False,0.67,Medium
51,52,1,0.5,0.5,0.2,True,False,False,False,0.67,Medium
196,197,1,0.5,0.5,0.2,False,True,False,False,0.67,Medium
115,116,1,0.5,0.2,0.7,True,False,False,False,0.66,Medium
157,158,1,0.5,0.2,0.7,True,False,False,False,0.66,Medium
159,160,1,0.5,0.2,0.2,False,False,False,True,0.61,Medium
80,81,1,0.5,0.2,0.2,False,True,False,False,0.61,Medium
11,12,1,0.0,0.7,0.7,True,False,False,False,0.61,Medium
120,121,1,0.0,0.7,0.7,False,False,False,False,0.61,Medium
150,151,1,0.0,0.5,1.0,True,False,False,False,0.60,Medium
127,128,1,0.0,0.5,1.0,False,True,False,False,0.60,Medium
186,187,1,0.0,0.5,1.0,True,False,False,False,0.60,Medium
62,63,1,0.0,0.5,1.0,False,False,True,False,0.60,Medium
75,76,1,0.0,0.5,1.0,False,False,False,True,0.60,Medium
34,35,1,0.0,0.5,1.0,True,False,False,False,0.60,Medium
86,87,1,0.0,0.5,0.7,False,False,False,True,0.57,Medium
197,198,1,0.0,0.5,0.7,False,False,False,False,0.57,Medium
113,114,1,0.0,0.5,0.7,False,False,False,False,0.57,Medium

In [29]:
#اذا بدي اعلى 50 بالاولوية مع عرض بعض الاعمدة المهمة
df = df.sort_values(by='PriorityScore', ascending=False)
top_50 = df.head(50)
top_50[['FamilyID', 'PriorityScore', 'PriorityLevel']]

     FamilyID  PriorityScore PriorityLevel
137       138           0.94          High
74         75           0.91          High
104       105           0.90          High
140       141           0.90          High
165       166           0.90          High
134       135           0.90          High
192       193           0.90          High
43         44           0.87          High
92         93           0.87          High
69         70           0.87          High
9          10           0.87          High
139       140           0.87          High
182       183           0.84          High
88         89           0.82          High
116       117           0.82          High
1           2           0.82          High
52         53           0.81          High
50         51           0.81          High
73         74           0.76        Medium
198       199           0.75        Medium
53         54           0.75        Medium
67         68           0.75        Medium
35         36           0.75        Medium
2           3           0.75        Medium
91         92           0.72        Medium
118       119           0.72        Medium
25         26           0.72        Medium
199       200           0.72        Medium
191       192           0.72        Medium
183       184           0.72        Medium
126       127           0.72        Medium
178       179           0.72        Medium
33         34           0.67        Medium
51         52           0.67        Medium
196       197           0.67        Medium
115       116           0.66        Medium
157       158           0.66        Medium
159       160           0.61        Medium
80         81           0.61        Medium
11         12           0.61        Medium
120       121           0.61        Medium
150       151           0.60        Medium
127       128           0.60        Medium
186       187           0.60        Medium
62         63           0.60        Medium
75         76           0.60        Medium
34         35           0.60        Medium
86         87           0.57        Medium
197       198           0.57        Medium
113       114           0.57        Medium

In [30]:

import os

BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), ".."))

save_path = os.path.join(BASE_DIR, "data", "processed")

os.makedirs(save_path, exist_ok=True)

top_50.to_csv(os.path.join(save_path, "top_50.csv"), index=False)

# CSV   حفظت أعلى 50 عائلات   في مجلد البيانات المعالجة في ملف  
# النقطتين في المسار تعني ارجع مجلد واحد للخلف حتى يحفظ في مجلد المشروع وليس داخل مجلد notebooke

In [ ]:


X = df[
    [
        "SpecialCase",
        "Income",
        "FamilyMembers",
        "Housing"
    ]
]

y = df["PriorityScore"]

X = X.astype(float)

X (Features) → المعلومات التي نُدخلها للنموذج
y (Target) → النتيجة التي نريد من النموذج التنبؤ بها

ماذا يفعل؟

 df اسمه DataFrame  يأخذ
يحذف عمودين:

PriorityScore
PriorityLevel

 X  ويضع بقية الأعمدة في متغير اسمه 

 لماذا نحذف هذه الأعمدة؟
لأن:

PriorityScore هو الهدف (Target)
PriorityLevel غالبًا مشتق من PriorityScore
(مثل: High / Medium / Low)

❗ إذا تركناهم داخل X:

النموذج سيغش ✅
سيتعلم الإجابة بدل التنبؤ بها
(يسمى هذا Data Leakage)

ماذا يمثل y؟

هو Target Variable
القيمة التي نريد من النموذج أن يتعلم التنبؤ بها

استبدال الاكواد من تقسيم البيانات الى حفظ النموذج بالاكواد التالية لتحسين النموذج باستخدام :
RandomForestRegressor

In [32]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

# 1. Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# 2. Split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)


# -----------------------------
# Linear Regression
# -----------------------------
lr_model = LinearRegression()

lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)

lr_mae = mean_absolute_error(y_test, lr_pred)

lr_r2 = r2_score(y_test, lr_pred)

print(f"Linear Regression MAE: {lr_mae:.4f}")
print(f"Linear Regression R²: {lr_r2 * 100:.2f}%")

print("####################")

# -----------------------------
# Random Forest
# -----------------------------
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

rf_mae = mean_absolute_error(y_test, rf_pred)

rf_r2 = r2_score(y_test, rf_pred)

print(f"Random Forest MAE: {rf_mae:.4f}")
print(f"Random Forest R²: {rf_r2 * 100:.2f}%")

Linear Regression MAE: 0.0000
Linear Regression R²: 100.00%
####################
Random Forest MAE: 0.0057
Random Forest R²: 99.59%

“حقق 
Linear Regression 
أقل خطأ لأنه مناسب للعلاقات الخطية المستخدمة في حساب 
PriorityScore، 
بينما أظهر 
Random Forest 
قدرة جيدة على فهم العلاقات المعقدة مع فرق بسيط في الدقة.”

“تم إنشاء PriorityScore 
باستخدام معادلة تعتمد على الخصائص الاجتماعية والاقتصادية، ثم تم تدريب النموذج لتعلم هذا السلوك وتوقع الأولويات تلقائيًا.”

### R² Score هي Accuracy
 Regression لكن لا تقال بشكل مباشر في

In [33]:
import pandas as pd
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
})

importance.sort_values(by="Importance", ascending=False)

         Feature  Importance
0    SpecialCase    0.707889
1         Income    0.260373
2  FamilyMembers    0.015953
3        Housing    0.015785

⚠️ لماذا Region تأثيره شبه صفر؟

لأن:

البيانات غالبًا غير مرتبطة فعليًا بالمنطقة
أو التوزيع متشابه بين المناطق

🎯 وهذا طبيعي جدًا

ولا يعتبر خطأ

In [34]:

import pickle

with open("../models/priority_model.pkl", "wb") as f:
    pickle.dump(lr_model, f)

with open("../models/scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

قمنا بحفظ : 
1- model
2- scaler

لنستخدمهم في الخطوة التالية وهي : 
بناء API